name: dbuilder_mobile
description: DBuilder

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  jaguar_serializer: 2.2.12
  http: 0.12.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true